import type { NewsItem, NewsStats, PollStats } from '@pyn/core';

/**
 * Mock-данные раздела Новости. Покрывают: pinned + обычные, news + poll,
 * own + others, read + unread, разные presence отправителей, attachments.
 */

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: 1,
    kind: 'news',
    senderLogin: 'jon',
    senderName: 'Jon',
    senderInitials: 'J',
    senderAvatarUrl: '',
    senderPresence: 'online',
    text: 'Завтра общий митап в 10:00 — не забываем подготовить отчёты за неделю.',
    createdAt: '2026-05-15T08:00:00Z',
    createdAtLabel: 'вчера в 11:00',
    isRead: true,
    isPinned: true,
    reactions: { '👍': 12, '🔥': 3 },
    myReactions: [],
    attachments: [],
    poll: null,
    isOwn: true,
  },
  {
    id: 2,
    kind: 'poll',
    senderLogin: 'anna',
    senderName: 'Анна Соколова',
    senderInitials: 'АС',
    senderAvatarUrl: '',
    senderPresence: 'online',
    text: '',
    createdAt: '2026-05-15T10:30:00Z',
    createdAtLabel: 'вчера в 13:30',
    isRead: true,
    isPinned: true,
    reactions: { '👀': 5 },
    myReactions: ['👀'],
    attachments: [],
    poll: {
      id: 1,
      question: 'Какой день для выезда удобнее?',
      description: 'Опрос закроется в пятницу',
      options: [
        { id: 1, text: 'Понедельник',  votesCount: 4 },
        { id: 2, text: 'Среда',        votesCount: 8 },
        { id: 3, text: 'Пятница',      votesCount: 5 },
      ],
      myVoteOptionId: 2,
      totalVoters: 17,
      isActive: true,
    },
    isOwn: false,
  },
  {
    id: 3,
    kind: 'news',
    senderLogin: 'mikhail',
    senderName: 'Михаил Петров',
    senderInitials: 'МП',
    senderAvatarUrl: '',
    senderPresence: 'offline',
    text: 'Обновили внутренний регламент по складу. Файл во вложении — пожалуйста, ознакомьтесь до конца недели.',
    createdAt: '2026-05-16T09:15:00Z',
    createdAtLabel: 'сегодня в 12:15',
    isRead: true,
    isPinned: false,
    reactions: { '👍': 3 },
    myReactions: ['👍'],
    attachments: [
      { id: 'a1', filename: 'Регламент-склад-v3.pdf', size: 451321, mimeType: 'application/pdf', url: '' },
    ],
    poll: null,
    isOwn: false,
  },
  {
    id: 4,
    kind: 'poll',
    senderLogin: 'ekaterina',
    senderName: 'Екатерина Волкова',
    senderInitials: 'ЕВ',
    senderAvatarUrl: '',
    senderPresence: 'online',
    text: '',
    createdAt: '2026-05-16T08:00:00Z',
    createdAtLabel: 'сегодня в 11:00',
    isRead: false,
    isPinned: false,
    reactions: {},
    myReactions: [],
    attachments: [],
    poll: {
      id: 2,
      question: 'Кофе или чай в офис?',
      description: '',
      options: [
        { id: 1, text: 'Только кофе',      votesCount: 7 },
        { id: 2, text: 'Только чай',       votesCount: 4 },
        { id: 3, text: 'И то, и другое',   votesCount: 11 },
      ],
      myVoteOptionId: null,
      totalVoters: 22,
      isActive: true,
    },
    isOwn: false,
  },
  {
    id: 5,
    kind: 'news',
    senderLogin: 'dmitry',
    senderName: 'Дмитрий Соловьёв',
    senderInitials: 'ДС',
    senderAvatarUrl: '',
    senderPresence: 'away',
    text: 'С праздником, коллеги! Желаю всем продуктивной недели.',
    createdAt: '2026-05-13T07:00:00Z',
    createdAtLabel: '13.05',
    isRead: true,
    isPinned: false,
    reactions: { '🎉': 18, '❤️': 7, '🙏': 4 },
    myReactions: ['🎉', '❤️'],
    attachments: [],
    poll: null,
    isOwn: false,
  },
  {
    id: 6,
    kind: 'news',
    senderLogin: 'admin',
    senderName: 'Администратор',
    senderInitials: 'А',
    senderAvatarUrl: '',
    senderPresence: 'online',
    text: 'Уведомление: завтра плановое техническое обслуживание сервера с 22:00 до 02:00. На это время сервис будет недоступен.',
    createdAt: '2026-05-16T14:00:00Z',
    createdAtLabel: 'только что',
    isRead: false,
    isPinned: false,
    reactions: {},
    myReactions: [],
    attachments: [],
    poll: null,
    isOwn: false,
  },
];

/** Статистика news, индексируется по NewsItem.id. */
export const NEWS_STATS: Record<number, NewsStats> = {
  1: {
    readers: [
      { userId: 'anna',      name: 'Анна Соколова',    initials: 'АС', readAtLabel: '15.05 11:05' },
      { userId: 'mikhail',   name: 'Михаил Петров',    initials: 'МП', readAtLabel: '15.05 11:12' },
      { userId: 'ekaterina', name: 'Екатерина Волкова', initials: 'ЕВ', readAtLabel: '15.05 11:45' },
    ],
    notReaders: [
      { userId: 'dmitry', name: 'Дмитрий Соловьёв', initials: 'ДС' },
      { userId: 'sergey', name: 'Сергей Кузнецов',  initials: 'СК' },
    ],
  },
  3: {
    readers: [
      { userId: 'jon',  name: 'Jon',            initials: 'J',  readAtLabel: '16.05 12:18' },
      { userId: 'anna', name: 'Анна Соколова',  initials: 'АС', readAtLabel: '16.05 12:20' },
    ],
    notReaders: [
      { userId: 'ekaterina', name: 'Екатерина Волкова', initials: 'ЕВ' },
      { userId: 'dmitry',    name: 'Дмитрий Соловьёв',  initials: 'ДС' },
      { userId: 'sergey',    name: 'Сергей Кузнецов',   initials: 'СК' },
    ],
  },
  5: {
    readers: [
      { userId: 'jon',       name: 'Jon',               initials: 'J',  readAtLabel: '13.05 07:30' },
      { userId: 'anna',      name: 'Анна Соколова',     initials: 'АС', readAtLabel: '13.05 08:15' },
      { userId: 'mikhail',   name: 'Михаил Петров',     initials: 'МП', readAtLabel: '13.05 09:00' },
      { userId: 'ekaterina', name: 'Екатерина Волкова', initials: 'ЕВ', readAtLabel: '13.05 09:22' },
    ],
    notReaders: [],
  },
  6: {
    readers: [],
    notReaders: [
      { userId: 'jon',       name: 'Jon',              initials: 'J' },
      { userId: 'anna',      name: 'Анна Соколова',    initials: 'АС' },
      { userId: 'mikhail',   name: 'Михаил Петров',    initials: 'МП' },
      { userId: 'ekaterina', name: 'Екатерина Волкова', initials: 'ЕВ' },
      { userId: 'dmitry',    name: 'Дмитрий Соловьёв', initials: 'ДС' },
    ],
  },
};

/** Статистика poll, индексируется по NewsItem.id (а не Poll.id, для удобства lookup'a в карточке). */
export const POLL_STATS: Record<number, PollStats> = {
  2: {
    voters: [
      { userId: 'jon',     name: 'Jon',           initials: 'J',  votedOptionIds: [2], votedOptionTexts: [], votedAtLabel: '15.05 14:00' },
      { userId: 'mikhail', name: 'Михаил Петров', initials: 'МП', votedOptionIds: [1], votedOptionTexts: [], votedAtLabel: '15.05 14:12' },
      { userId: 'anna',    name: 'Анна Соколова', initials: 'АС', votedOptionIds: [2], votedOptionTexts: [], votedAtLabel: '15.05 15:01' },
    ],
    notVoters: [
      { userId: 'sergey', name: 'Сергей Кузнецов', initials: 'СК' },
    ],
    optionsById: { 1: 'Да', 2: 'Нет' },
  },
  4: {
    voters: [
      { userId: 'mikhail', name: 'Михаил Петров',    initials: 'МП', votedOptionIds: [3], votedOptionTexts: [], votedAtLabel: '16.05 11:05' },
      { userId: 'anna',    name: 'Анна Соколова',    initials: 'АС', votedOptionIds: [1], votedOptionTexts: [], votedAtLabel: '16.05 11:15' },
      { userId: 'dmitry',  name: 'Дмитрий Соловьёв', initials: 'ДС', votedOptionIds: [3], votedOptionTexts: [], votedAtLabel: '16.05 11:32' },
    ],
    notVoters: [
      { userId: 'jon',       name: 'Jon',               initials: 'J' },
      { userId: 'ekaterina', name: 'Екатерина Волкова', initials: 'ЕВ' },
    ],
    optionsById: { 1: 'Pyn', 2: 'OTLHelper', 3: 'Третий вариант' },
  },
};
